name:                example
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/leptonyu/yam/example#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

executables:
  yam:
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - yam
      - servant-server
      - monad-logger
      - salak
      - http-types
      - text
      - swagger2
      - lens

defaults:
  local: ../defaults.yaml
