_common: !include "../common.yaml"
<<: *legal
name:                example
version:             0.1.0.0
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5

executables:
  yam:
    when:
    - condition: os(linux)
      ld-options:     -static
    source-dirs:      src
    main:             Main.hs
    dependencies:
      - yam
      - servant-server
      - servant-swagger
      - monad-logger
      - salak
      - salak-yaml
      - yam-redis
      - text
      - vault