resolver: nightly-2019-07-24
packages:
- yam
- yam-datasource
- yam-redis
- example
extra-deps:
  #- ../salak/salak
  #- ../salak/salak-yaml
- salak-0.3
- salak-yaml-0.3
- persistent-2.10.0

pvp-bounds: both
nix:
  packages:
  - zlib
  - lzma
