resolver: nightly-2019-04-16
packages:
- yam
- yam-datasource
- yam-redis
- example
extra-deps:
- persistent-2.10.0
- salak-0.2.9.1
- salak-yaml-0.2.9.1

pvp-bounds: both
nix:
  packages:
  - zlib
  - lzma
