resolver: nightly-2019-07-25
packages:
- yam
- yam-datasource
- yam-redis
# - ../boots
  #- example
extra-deps:
- boots-0.0.2
- salak-0.3.1
- salak-yaml-0.3.1
- persistent-2.10.0

pvp-bounds: both
nix:
  packages:
  - zlib
  - lzma
