name:                yam-datasource
version:             0.6.0
synopsis:            Yam DataSource Middleware
#description:
homepage:            https://github.com/leptonyu/yam/yam-datasource#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) Daniel YU
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - yam
  - unliftio-core
  - resourcet
  - conduit
  - persistent >=2.8.0 && <2.11
  - resource-pool
  - monad-logger
  - text
  - servant-server
  - salak
  - data-default

library:
  source-dirs: src
  exposed-modules:
    - Yam.DataSource

defaults:
  local: ../defaults.yaml
