_common: !include "../common.yaml"
<<: *legal
name:                yam-datasource
synopsis:            Yam DataSource Middleware

extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - yam
  - unliftio-core
  - resourcet
  - conduit
  - persistent >=2.8.0 && <2.11
  - resource-pool
  - monad-logger
  - text
  - servant-server
  - salak >= 0.3
  - data-default

library:
  source-dirs: src
  exposed-modules:
    - Yam.DataSource
