name:                yam-datasource
version:             0.5.5
synopsis:            Yam DataSource Middleware
#description:
homepage:            https://github.com/leptonyu/yam/yam-datasource#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) Daniel YU
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.11 && < 5
  - yam
  - unliftio-core
  - resourcet
  - conduit
  - persistent
  - resource-pool

library:
  source-dirs: src
  exposed-modules:
    - Yam.DataSource

defaults:
  local: ../defaults.yaml
