name:                yam
version:             0.6.1
synopsis:            A wrapper of servant
description:         A out-of-the-box wrapper of [servant](https://hackage.haskell.org/package/servant-server).
homepage:            https://github.com/leptonyu/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md
- yam_test.yml

dependencies:
  - base >= 4.10 && < 5
  - salak >= 0.2.9 && < 0.3
  - aeson
  - text
  - bytestring
  - base16-bytestring
  - binary
  - mwc-random
  - mtl
  - scientific
  - unordered-containers
  - unliftio-core
  - lens
  - reflection
  - data-default
  - vault
  - monad-logger
  - fast-logger
  - wai
  - warp
  - http-types
  - servant-server >= 0.16 && < 0.17
  - servant-client >= 0.16 && < 0.17
  - http-client
  - servant-swagger
  - servant-swagger-ui
  - swagger2
  - vector
  - menshen

library:
  source-dirs: src
  exposed-modules:
    - Yam
    - Yam.Middleware.Client

  other-modules:
    - Yam.Swagger
    - Yam.Logger
    - Yam.App
    
    - Yam.Prelude
    - Yam.Config

    - Yam.Middleware
    - Yam.Middleware.Trace
    - Yam.Middleware.Error
    
    - Yam.Server
    - Yam.Server.Refresh
    
    - Data.Opentracing
    - Data.Opentracing.Types
    - Data.Opentracing.Tracer
    - Data.Opentracing.Simple

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck < 2.14
      - text

defaults:
  local: ../defaults.yaml
