name:                yam
version:             0.5.7
synopsis:            Yam Web
#description:
homepage:            https://github.com/leptonyu/yam/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) 2018 Daniel YU
category:            Web
extra-source-files:
- README.md
- yam_test.yml

dependencies:
  - base >= 4.11 && < 5
  - salak >= 0.1.4 && < 0.3
  - text
  - bytestring
  - base16-bytestring
  - binary
  - mwc-random
  - mtl
  - scientific
  - unordered-containers
  - unliftio-core
  - lens
  - reflection
  - data-default
  - vault
  - monad-logger
  - fast-logger
  - wai
  - wai-extra
  - warp
  - http-types
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - swagger2

library:
  source-dirs: src
  exposed-modules:
    - Yam
    - Yam.Internal
    - Yam.Middleware
    - Yam.Middleware.Default
    - Yam.Middleware.Auth
    - Yam.Middleware.Trace
    - Yam.Swagger
    - Yam.Types
    - Yam.Types.Prelude
    - Yam.Types.Env
    - Yam.Logger
  other-modules:
    - Data.Opentracing
    - Data.Opentracing.Types
    - Data.Opentracing.Tracer
    - Data.Opentracing.Simple

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - text

defaults:
  local: ../defaults.yaml
