_common: !include "../common.yaml"
<<: *legal
name:                yam-redis
synopsis:            Yam Redis Middleware
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - yam
  - salak >= 0.3
  - text
  - mtl
  - data-default
  - hedis
  - menshen
  - monad-logger
  - servant-server
  - bytestring

library:
  source-dirs: src
  exposed-modules:
    - Yam.Redis
