name:                yam-redis
version:             0.6.2
synopsis:            Yam Redis Middleware
#description:
homepage:            https://github.com/leptonyu/yam#readme
license:             BSD3
author:              Daniel YU
maintainer:          Daniel YU <leptonyu@gmail.com>
copyright:           (c) Daniel YU
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.10 && < 5
  - yam
  - salak >= 0.2.9.3
  - text
  - mtl
  - data-default
  - hedis
  - menshen
  - monad-logger
  - servant-server
  - bytestring

library:
  source-dirs: src
  exposed-modules:
    - Yam.Redis

defaults:
  local: ../defaults.yaml
